//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSynchro.ServerJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SynchroWeb/", ConfigurationName="ServerJava.PenduloWS")]
    public interface PenduloWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ActualizarProyectoRequest", ReplyAction="http://SynchroWeb/PenduloWS/ActualizarProyectoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ActualizarProyectoResponse ActualizarProyecto(ClienteSynchro.ServerJava.ActualizarProyectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ActualizarProyectoRequest", ReplyAction="http://SynchroWeb/PenduloWS/ActualizarProyectoResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ActualizarProyectoResponse> ActualizarProyectoAsync(ClienteSynchro.ServerJava.ActualizarProyectoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/helloRequest", ReplyAction="http://SynchroWeb/PenduloWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.helloResponse hello(ClienteSynchro.ServerJava.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/helloRequest", ReplyAction="http://SynchroWeb/PenduloWS/helloResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.helloResponse> helloAsync(ClienteSynchro.ServerJava.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ModificarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/ModificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ModificarUsuarioResponse ModificarUsuario(ClienteSynchro.ServerJava.ModificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ModificarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ModificarUsuarioResponse> ModificarUsuarioAsync(ClienteSynchro.ServerJava.ModificarUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/EliminarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/EliminarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.EliminarUsuarioResponse EliminarUsuario(ClienteSynchro.ServerJava.EliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/EliminarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.EliminarUsuarioResponse> EliminarUsuarioAsync(ClienteSynchro.ServerJava.EliminarUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.AgregarUsuarioResponse AgregarUsuario(ClienteSynchro.ServerJava.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarUsuarioResponse> AgregarUsuarioAsync(ClienteSynchro.ServerJava.AgregarUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerImagenRequest", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerImagenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ObtenerImagenResponse ObtenerImagen(ClienteSynchro.ServerJava.ObtenerImagenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerImagenRequest", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerImagenResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerImagenResponse> ObtenerImagenAsync(ClienteSynchro.ServerJava.ObtenerImagenRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarGrupoRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarGrupoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.AgregarGrupoResponse AgregarGrupo(ClienteSynchro.ServerJava.AgregarGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarGrupoRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarGrupoResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarGrupoResponse> AgregarGrupoAsync(ClienteSynchro.ServerJava.AgregarGrupoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarHabilidadRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarHabilidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.AgregarHabilidadResponse AgregarHabilidad(ClienteSynchro.ServerJava.AgregarHabilidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarHabilidadRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarHabilidadResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarHabilidadResponse> AgregarHabilidadAsync(ClienteSynchro.ServerJava.AgregarHabilidadRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarProyectoRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarProyectoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.AgregarProyectoResponse AgregarProyecto(ClienteSynchro.ServerJava.AgregarProyectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarProyectoRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarProyectoResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarProyectoResponse> AgregarProyectoAsync(ClienteSynchro.ServerJava.AgregarProyectoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/EliminsrProyectoRequest", ReplyAction="http://SynchroWeb/PenduloWS/EliminsrProyectoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.EliminsrProyectoResponse EliminsrProyecto(ClienteSynchro.ServerJava.EliminsrProyectoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/EliminsrProyectoRequest", ReplyAction="http://SynchroWeb/PenduloWS/EliminsrProyectoResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.EliminsrProyectoResponse> EliminsrProyectoAsync(ClienteSynchro.ServerJava.EliminsrProyectoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarTareaRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarTareaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.AgregarTareaResponse AgregarTarea(ClienteSynchro.ServerJava.AgregarTareaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarTareaRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarTareaResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarTareaResponse> AgregarTareaAsync(ClienteSynchro.ServerJava.AgregarTareaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerPass2Request", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerPass2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ObtenerPass2Response ObtenerPass2(ClienteSynchro.ServerJava.ObtenerPass2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerPass2Request", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerPass2Response")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerPass2Response> ObtenerPass2Async(ClienteSynchro.ServerJava.ObtenerPass2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ObtenerUsuarioResponse ObtenerUsuario(ClienteSynchro.ServerJava.ObtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerUsuarioResponse> ObtenerUsuarioAsync(ClienteSynchro.ServerJava.ObtenerUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerContraRequest", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerContraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ObtenerContraResponse ObtenerContra(ClienteSynchro.ServerJava.ObtenerContraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerContraRequest", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerContraResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerContraResponse> ObtenerContraAsync(ClienteSynchro.ServerJava.ObtenerContraRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerUsu2Request", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerUsu2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.ObtenerUsu2Response ObtenerUsu2(ClienteSynchro.ServerJava.ObtenerUsu2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/ObtenerUsu2Request", ReplyAction="http://SynchroWeb/PenduloWS/ObtenerUsu2Response")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerUsu2Response> ObtenerUsu2Async(ClienteSynchro.ServerJava.ObtenerUsu2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarConocimientoRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarConocimientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.AgregarConocimientoResponse AgregarConocimiento(ClienteSynchro.ServerJava.AgregarConocimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/AgregarConocimientoRequest", ReplyAction="http://SynchroWeb/PenduloWS/AgregarConocimientoResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarConocimientoResponse> AgregarConocimientoAsync(ClienteSynchro.ServerJava.AgregarConocimientoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/VerificarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/VerificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSynchro.ServerJava.VerificarUsuarioResponse VerificarUsuario(ClienteSynchro.ServerJava.VerificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SynchroWeb/PenduloWS/VerificarUsuarioRequest", ReplyAction="http://SynchroWeb/PenduloWS/VerificarUsuarioResponse")]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.VerificarUsuarioResponse> VerificarUsuarioAsync(ClienteSynchro.ServerJava.VerificarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProyecto", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ActualizarProyectoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string visibilidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responsable;
        
        public ActualizarProyectoRequest() {
        }
        
        public ActualizarProyectoRequest(string nombre, string estado, string monto, string visibilidad, string logo, string responsable) {
            this.nombre = nombre;
            this.estado = estado;
            this.monto = monto;
            this.visibilidad = visibilidad;
            this.logo = logo;
            this.responsable = responsable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarProyectoResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ActualizarProyectoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ActualizarProyectoResponse() {
        }
        
        public ActualizarProyectoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarUsuario", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ModificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string banco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imagen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        public ModificarUsuarioRequest() {
        }
        
        public ModificarUsuarioRequest(string nombre, string apellido, string usuario, string pass, string nacimiento, string banco, string imagen, string correo) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.usuario = usuario;
            this.pass = pass;
            this.nacimiento = nacimiento;
            this.banco = banco;
            this.imagen = imagen;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModificarUsuarioResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ModificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ModificarUsuarioResponse() {
        }
        
        public ModificarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarUsuario", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Alias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Correo;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(string Alias, string Correo) {
            this.Alias = Alias;
            this.Correo = Correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarUsuarioResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarUsuario", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imagen;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(string nombre, string apellido, string correo, string usuario, string pass, string nacimiento, string imagen) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.correo = correo;
            this.usuario = usuario;
            this.pass = pass;
            this.nacimiento = nacimiento;
            this.imagen = imagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarUsuarioResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerImagen", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerImagenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public ObtenerImagenRequest() {
        }
        
        public ObtenerImagenRequest(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerImagenResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerImagenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ObtenerImagenResponse() {
        }
        
        public ObtenerImagenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarGrupo", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lider;
        
        public AgregarGrupoRequest() {
        }
        
        public AgregarGrupoRequest(string nombre, string descripcion, string logo, string lider) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.logo = logo;
            this.lider = lider;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarGrupoResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarGrupoResponse() {
        }
        
        public AgregarGrupoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarHabilidad", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarHabilidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public AgregarHabilidadRequest() {
        }
        
        public AgregarHabilidadRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarHabilidadResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarHabilidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarHabilidadResponse() {
        }
        
        public AgregarHabilidadResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarProyecto", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarProyectoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responsable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string costo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string visibilidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logo;
        
        public AgregarProyectoRequest() {
        }
        
        public AgregarProyectoRequest(string nombre, string responsable, string estado, string costo, string visibilidad, string logo) {
            this.nombre = nombre;
            this.responsable = responsable;
            this.estado = estado;
            this.costo = costo;
            this.visibilidad = visibilidad;
            this.logo = logo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarProyectoResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarProyectoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarProyectoResponse() {
        }
        
        public AgregarProyectoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminsrProyecto", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class EliminsrProyectoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responsable;
        
        public EliminsrProyectoRequest() {
        }
        
        public EliminsrProyectoRequest(string nombre, string responsable) {
            this.nombre = nombre;
            this.responsable = responsable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminsrProyectoResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class EliminsrProyectoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public EliminsrProyectoResponse() {
        }
        
        public EliminsrProyectoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarTarea", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarTareaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string participantes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pertenece;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string visibilidad;
        
        public AgregarTareaRequest() {
        }
        
        public AgregarTareaRequest(string nombre, string estado, string participantes, string monto, string pertenece, string visibilidad) {
            this.nombre = nombre;
            this.estado = estado;
            this.participantes = participantes;
            this.monto = monto;
            this.pertenece = pertenece;
            this.visibilidad = visibilidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarTareaResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarTareaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarTareaResponse() {
        }
        
        public AgregarTareaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPass2", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerPass2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public ObtenerPass2Request() {
        }
        
        public ObtenerPass2Request(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPass2Response", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerPass2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ObtenerPass2Response() {
        }
        
        public ObtenerPass2Response(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SynchroWeb/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string correoField;
        
        private string imagenField;
        
        private string nacimientoField;
        
        private string nombreField;
        
        private string passwordField;
        
        private string usuario1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("imagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacimiento {
            get {
                return this.nacimientoField;
            }
            set {
                this.nacimientoField = value;
                this.RaisePropertyChanged("nacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
                this.RaisePropertyChanged("usuario1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuario", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public ObtenerUsuarioRequest() {
        }
        
        public ObtenerUsuarioRequest(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuarioResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSynchro.ServerJava.usuario @return;
        
        public ObtenerUsuarioResponse() {
        }
        
        public ObtenerUsuarioResponse(ClienteSynchro.ServerJava.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerContra", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerContraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public ObtenerContraRequest() {
        }
        
        public ObtenerContraRequest(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerContraResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerContraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSynchro.ServerJava.usuario @return;
        
        public ObtenerContraResponse() {
        }
        
        public ObtenerContraResponse(ClienteSynchro.ServerJava.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsu2", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerUsu2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public ObtenerUsu2Request() {
        }
        
        public ObtenerUsu2Request(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsu2Response", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class ObtenerUsu2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ObtenerUsu2Response() {
        }
        
        public ObtenerUsu2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarConocimiento", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarConocimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        public AgregarConocimientoRequest() {
        }
        
        public AgregarConocimientoRequest(string nombre, string usuario) {
            this.nombre = nombre;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarConocimientoResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class AgregarConocimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public AgregarConocimientoResponse() {
        }
        
        public AgregarConocimientoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarUsuario", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class VerificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public VerificarUsuarioRequest() {
        }
        
        public VerificarUsuarioRequest(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarUsuarioResponse", WrapperNamespace="http://SynchroWeb/", IsWrapped=true)]
    public partial class VerificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SynchroWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public VerificarUsuarioResponse() {
        }
        
        public VerificarUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PenduloWSChannel : ClienteSynchro.ServerJava.PenduloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PenduloWSClient : System.ServiceModel.ClientBase<ClienteSynchro.ServerJava.PenduloWS>, ClienteSynchro.ServerJava.PenduloWS {
        
        public PenduloWSClient() {
        }
        
        public PenduloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PenduloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PenduloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PenduloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ActualizarProyectoResponse ClienteSynchro.ServerJava.PenduloWS.ActualizarProyecto(ClienteSynchro.ServerJava.ActualizarProyectoRequest request) {
            return base.Channel.ActualizarProyecto(request);
        }
        
        public string ActualizarProyecto(string nombre, string estado, string monto, string visibilidad, string logo, string responsable) {
            ClienteSynchro.ServerJava.ActualizarProyectoRequest inValue = new ClienteSynchro.ServerJava.ActualizarProyectoRequest();
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.monto = monto;
            inValue.visibilidad = visibilidad;
            inValue.logo = logo;
            inValue.responsable = responsable;
            ClienteSynchro.ServerJava.ActualizarProyectoResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ActualizarProyecto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ActualizarProyectoResponse> ClienteSynchro.ServerJava.PenduloWS.ActualizarProyectoAsync(ClienteSynchro.ServerJava.ActualizarProyectoRequest request) {
            return base.Channel.ActualizarProyectoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ActualizarProyectoResponse> ActualizarProyectoAsync(string nombre, string estado, string monto, string visibilidad, string logo, string responsable) {
            ClienteSynchro.ServerJava.ActualizarProyectoRequest inValue = new ClienteSynchro.ServerJava.ActualizarProyectoRequest();
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.monto = monto;
            inValue.visibilidad = visibilidad;
            inValue.logo = logo;
            inValue.responsable = responsable;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ActualizarProyectoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.helloResponse ClienteSynchro.ServerJava.PenduloWS.hello(ClienteSynchro.ServerJava.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ClienteSynchro.ServerJava.helloRequest inValue = new ClienteSynchro.ServerJava.helloRequest();
            inValue.name = name;
            ClienteSynchro.ServerJava.helloResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.helloResponse> ClienteSynchro.ServerJava.PenduloWS.helloAsync(ClienteSynchro.ServerJava.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.helloResponse> helloAsync(string name) {
            ClienteSynchro.ServerJava.helloRequest inValue = new ClienteSynchro.ServerJava.helloRequest();
            inValue.name = name;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ModificarUsuarioResponse ClienteSynchro.ServerJava.PenduloWS.ModificarUsuario(ClienteSynchro.ServerJava.ModificarUsuarioRequest request) {
            return base.Channel.ModificarUsuario(request);
        }
        
        public string ModificarUsuario(string nombre, string apellido, string usuario, string pass, string nacimiento, string banco, string imagen, string correo) {
            ClienteSynchro.ServerJava.ModificarUsuarioRequest inValue = new ClienteSynchro.ServerJava.ModificarUsuarioRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.usuario = usuario;
            inValue.pass = pass;
            inValue.nacimiento = nacimiento;
            inValue.banco = banco;
            inValue.imagen = imagen;
            inValue.correo = correo;
            ClienteSynchro.ServerJava.ModificarUsuarioResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ModificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ModificarUsuarioResponse> ClienteSynchro.ServerJava.PenduloWS.ModificarUsuarioAsync(ClienteSynchro.ServerJava.ModificarUsuarioRequest request) {
            return base.Channel.ModificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ModificarUsuarioResponse> ModificarUsuarioAsync(string nombre, string apellido, string usuario, string pass, string nacimiento, string banco, string imagen, string correo) {
            ClienteSynchro.ServerJava.ModificarUsuarioRequest inValue = new ClienteSynchro.ServerJava.ModificarUsuarioRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.usuario = usuario;
            inValue.pass = pass;
            inValue.nacimiento = nacimiento;
            inValue.banco = banco;
            inValue.imagen = imagen;
            inValue.correo = correo;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ModificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.EliminarUsuarioResponse ClienteSynchro.ServerJava.PenduloWS.EliminarUsuario(ClienteSynchro.ServerJava.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public string EliminarUsuario(string Alias, string Correo) {
            ClienteSynchro.ServerJava.EliminarUsuarioRequest inValue = new ClienteSynchro.ServerJava.EliminarUsuarioRequest();
            inValue.Alias = Alias;
            inValue.Correo = Correo;
            ClienteSynchro.ServerJava.EliminarUsuarioResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).EliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.EliminarUsuarioResponse> ClienteSynchro.ServerJava.PenduloWS.EliminarUsuarioAsync(ClienteSynchro.ServerJava.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.EliminarUsuarioResponse> EliminarUsuarioAsync(string Alias, string Correo) {
            ClienteSynchro.ServerJava.EliminarUsuarioRequest inValue = new ClienteSynchro.ServerJava.EliminarUsuarioRequest();
            inValue.Alias = Alias;
            inValue.Correo = Correo;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).EliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.AgregarUsuarioResponse ClienteSynchro.ServerJava.PenduloWS.AgregarUsuario(ClienteSynchro.ServerJava.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public string AgregarUsuario(string nombre, string apellido, string correo, string usuario, string pass, string nacimiento, string imagen) {
            ClienteSynchro.ServerJava.AgregarUsuarioRequest inValue = new ClienteSynchro.ServerJava.AgregarUsuarioRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.correo = correo;
            inValue.usuario = usuario;
            inValue.pass = pass;
            inValue.nacimiento = nacimiento;
            inValue.imagen = imagen;
            ClienteSynchro.ServerJava.AgregarUsuarioResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarUsuarioResponse> ClienteSynchro.ServerJava.PenduloWS.AgregarUsuarioAsync(ClienteSynchro.ServerJava.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarUsuarioResponse> AgregarUsuarioAsync(string nombre, string apellido, string correo, string usuario, string pass, string nacimiento, string imagen) {
            ClienteSynchro.ServerJava.AgregarUsuarioRequest inValue = new ClienteSynchro.ServerJava.AgregarUsuarioRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.correo = correo;
            inValue.usuario = usuario;
            inValue.pass = pass;
            inValue.nacimiento = nacimiento;
            inValue.imagen = imagen;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ObtenerImagenResponse ClienteSynchro.ServerJava.PenduloWS.ObtenerImagen(ClienteSynchro.ServerJava.ObtenerImagenRequest request) {
            return base.Channel.ObtenerImagen(request);
        }
        
        public string ObtenerImagen(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerImagenRequest inValue = new ClienteSynchro.ServerJava.ObtenerImagenRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            ClienteSynchro.ServerJava.ObtenerImagenResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerImagen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerImagenResponse> ClienteSynchro.ServerJava.PenduloWS.ObtenerImagenAsync(ClienteSynchro.ServerJava.ObtenerImagenRequest request) {
            return base.Channel.ObtenerImagenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerImagenResponse> ObtenerImagenAsync(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerImagenRequest inValue = new ClienteSynchro.ServerJava.ObtenerImagenRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerImagenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.AgregarGrupoResponse ClienteSynchro.ServerJava.PenduloWS.AgregarGrupo(ClienteSynchro.ServerJava.AgregarGrupoRequest request) {
            return base.Channel.AgregarGrupo(request);
        }
        
        public string AgregarGrupo(string nombre, string descripcion, string logo, string lider) {
            ClienteSynchro.ServerJava.AgregarGrupoRequest inValue = new ClienteSynchro.ServerJava.AgregarGrupoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.logo = logo;
            inValue.lider = lider;
            ClienteSynchro.ServerJava.AgregarGrupoResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarGrupo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarGrupoResponse> ClienteSynchro.ServerJava.PenduloWS.AgregarGrupoAsync(ClienteSynchro.ServerJava.AgregarGrupoRequest request) {
            return base.Channel.AgregarGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarGrupoResponse> AgregarGrupoAsync(string nombre, string descripcion, string logo, string lider) {
            ClienteSynchro.ServerJava.AgregarGrupoRequest inValue = new ClienteSynchro.ServerJava.AgregarGrupoRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.logo = logo;
            inValue.lider = lider;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarGrupoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.AgregarHabilidadResponse ClienteSynchro.ServerJava.PenduloWS.AgregarHabilidad(ClienteSynchro.ServerJava.AgregarHabilidadRequest request) {
            return base.Channel.AgregarHabilidad(request);
        }
        
        public string AgregarHabilidad(string nombre) {
            ClienteSynchro.ServerJava.AgregarHabilidadRequest inValue = new ClienteSynchro.ServerJava.AgregarHabilidadRequest();
            inValue.nombre = nombre;
            ClienteSynchro.ServerJava.AgregarHabilidadResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarHabilidad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarHabilidadResponse> ClienteSynchro.ServerJava.PenduloWS.AgregarHabilidadAsync(ClienteSynchro.ServerJava.AgregarHabilidadRequest request) {
            return base.Channel.AgregarHabilidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarHabilidadResponse> AgregarHabilidadAsync(string nombre) {
            ClienteSynchro.ServerJava.AgregarHabilidadRequest inValue = new ClienteSynchro.ServerJava.AgregarHabilidadRequest();
            inValue.nombre = nombre;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarHabilidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.AgregarProyectoResponse ClienteSynchro.ServerJava.PenduloWS.AgregarProyecto(ClienteSynchro.ServerJava.AgregarProyectoRequest request) {
            return base.Channel.AgregarProyecto(request);
        }
        
        public string AgregarProyecto(string nombre, string responsable, string estado, string costo, string visibilidad, string logo) {
            ClienteSynchro.ServerJava.AgregarProyectoRequest inValue = new ClienteSynchro.ServerJava.AgregarProyectoRequest();
            inValue.nombre = nombre;
            inValue.responsable = responsable;
            inValue.estado = estado;
            inValue.costo = costo;
            inValue.visibilidad = visibilidad;
            inValue.logo = logo;
            ClienteSynchro.ServerJava.AgregarProyectoResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarProyecto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarProyectoResponse> ClienteSynchro.ServerJava.PenduloWS.AgregarProyectoAsync(ClienteSynchro.ServerJava.AgregarProyectoRequest request) {
            return base.Channel.AgregarProyectoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarProyectoResponse> AgregarProyectoAsync(string nombre, string responsable, string estado, string costo, string visibilidad, string logo) {
            ClienteSynchro.ServerJava.AgregarProyectoRequest inValue = new ClienteSynchro.ServerJava.AgregarProyectoRequest();
            inValue.nombre = nombre;
            inValue.responsable = responsable;
            inValue.estado = estado;
            inValue.costo = costo;
            inValue.visibilidad = visibilidad;
            inValue.logo = logo;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarProyectoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.EliminsrProyectoResponse ClienteSynchro.ServerJava.PenduloWS.EliminsrProyecto(ClienteSynchro.ServerJava.EliminsrProyectoRequest request) {
            return base.Channel.EliminsrProyecto(request);
        }
        
        public string EliminsrProyecto(string nombre, string responsable) {
            ClienteSynchro.ServerJava.EliminsrProyectoRequest inValue = new ClienteSynchro.ServerJava.EliminsrProyectoRequest();
            inValue.nombre = nombre;
            inValue.responsable = responsable;
            ClienteSynchro.ServerJava.EliminsrProyectoResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).EliminsrProyecto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.EliminsrProyectoResponse> ClienteSynchro.ServerJava.PenduloWS.EliminsrProyectoAsync(ClienteSynchro.ServerJava.EliminsrProyectoRequest request) {
            return base.Channel.EliminsrProyectoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.EliminsrProyectoResponse> EliminsrProyectoAsync(string nombre, string responsable) {
            ClienteSynchro.ServerJava.EliminsrProyectoRequest inValue = new ClienteSynchro.ServerJava.EliminsrProyectoRequest();
            inValue.nombre = nombre;
            inValue.responsable = responsable;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).EliminsrProyectoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.AgregarTareaResponse ClienteSynchro.ServerJava.PenduloWS.AgregarTarea(ClienteSynchro.ServerJava.AgregarTareaRequest request) {
            return base.Channel.AgregarTarea(request);
        }
        
        public string AgregarTarea(string nombre, string estado, string participantes, string monto, string pertenece, string visibilidad) {
            ClienteSynchro.ServerJava.AgregarTareaRequest inValue = new ClienteSynchro.ServerJava.AgregarTareaRequest();
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.participantes = participantes;
            inValue.monto = monto;
            inValue.pertenece = pertenece;
            inValue.visibilidad = visibilidad;
            ClienteSynchro.ServerJava.AgregarTareaResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarTarea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarTareaResponse> ClienteSynchro.ServerJava.PenduloWS.AgregarTareaAsync(ClienteSynchro.ServerJava.AgregarTareaRequest request) {
            return base.Channel.AgregarTareaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarTareaResponse> AgregarTareaAsync(string nombre, string estado, string participantes, string monto, string pertenece, string visibilidad) {
            ClienteSynchro.ServerJava.AgregarTareaRequest inValue = new ClienteSynchro.ServerJava.AgregarTareaRequest();
            inValue.nombre = nombre;
            inValue.estado = estado;
            inValue.participantes = participantes;
            inValue.monto = monto;
            inValue.pertenece = pertenece;
            inValue.visibilidad = visibilidad;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarTareaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ObtenerPass2Response ClienteSynchro.ServerJava.PenduloWS.ObtenerPass2(ClienteSynchro.ServerJava.ObtenerPass2Request request) {
            return base.Channel.ObtenerPass2(request);
        }
        
        public string ObtenerPass2(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerPass2Request inValue = new ClienteSynchro.ServerJava.ObtenerPass2Request();
            inValue.usuario = usuario;
            inValue.pass = pass;
            ClienteSynchro.ServerJava.ObtenerPass2Response retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerPass2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerPass2Response> ClienteSynchro.ServerJava.PenduloWS.ObtenerPass2Async(ClienteSynchro.ServerJava.ObtenerPass2Request request) {
            return base.Channel.ObtenerPass2Async(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerPass2Response> ObtenerPass2Async(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerPass2Request inValue = new ClienteSynchro.ServerJava.ObtenerPass2Request();
            inValue.usuario = usuario;
            inValue.pass = pass;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerPass2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ObtenerUsuarioResponse ClienteSynchro.ServerJava.PenduloWS.ObtenerUsuario(ClienteSynchro.ServerJava.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuario(request);
        }
        
        public ClienteSynchro.ServerJava.usuario ObtenerUsuario(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerUsuarioRequest inValue = new ClienteSynchro.ServerJava.ObtenerUsuarioRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            ClienteSynchro.ServerJava.ObtenerUsuarioResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerUsuarioResponse> ClienteSynchro.ServerJava.PenduloWS.ObtenerUsuarioAsync(ClienteSynchro.ServerJava.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerUsuarioResponse> ObtenerUsuarioAsync(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerUsuarioRequest inValue = new ClienteSynchro.ServerJava.ObtenerUsuarioRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ObtenerContraResponse ClienteSynchro.ServerJava.PenduloWS.ObtenerContra(ClienteSynchro.ServerJava.ObtenerContraRequest request) {
            return base.Channel.ObtenerContra(request);
        }
        
        public ClienteSynchro.ServerJava.usuario ObtenerContra(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerContraRequest inValue = new ClienteSynchro.ServerJava.ObtenerContraRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            ClienteSynchro.ServerJava.ObtenerContraResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerContra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerContraResponse> ClienteSynchro.ServerJava.PenduloWS.ObtenerContraAsync(ClienteSynchro.ServerJava.ObtenerContraRequest request) {
            return base.Channel.ObtenerContraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerContraResponse> ObtenerContraAsync(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerContraRequest inValue = new ClienteSynchro.ServerJava.ObtenerContraRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerContraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.ObtenerUsu2Response ClienteSynchro.ServerJava.PenduloWS.ObtenerUsu2(ClienteSynchro.ServerJava.ObtenerUsu2Request request) {
            return base.Channel.ObtenerUsu2(request);
        }
        
        public string ObtenerUsu2(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerUsu2Request inValue = new ClienteSynchro.ServerJava.ObtenerUsu2Request();
            inValue.usuario = usuario;
            inValue.pass = pass;
            ClienteSynchro.ServerJava.ObtenerUsu2Response retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerUsu2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerUsu2Response> ClienteSynchro.ServerJava.PenduloWS.ObtenerUsu2Async(ClienteSynchro.ServerJava.ObtenerUsu2Request request) {
            return base.Channel.ObtenerUsu2Async(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.ObtenerUsu2Response> ObtenerUsu2Async(string usuario, string pass) {
            ClienteSynchro.ServerJava.ObtenerUsu2Request inValue = new ClienteSynchro.ServerJava.ObtenerUsu2Request();
            inValue.usuario = usuario;
            inValue.pass = pass;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).ObtenerUsu2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.AgregarConocimientoResponse ClienteSynchro.ServerJava.PenduloWS.AgregarConocimiento(ClienteSynchro.ServerJava.AgregarConocimientoRequest request) {
            return base.Channel.AgregarConocimiento(request);
        }
        
        public string AgregarConocimiento(string nombre, string usuario) {
            ClienteSynchro.ServerJava.AgregarConocimientoRequest inValue = new ClienteSynchro.ServerJava.AgregarConocimientoRequest();
            inValue.nombre = nombre;
            inValue.usuario = usuario;
            ClienteSynchro.ServerJava.AgregarConocimientoResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarConocimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarConocimientoResponse> ClienteSynchro.ServerJava.PenduloWS.AgregarConocimientoAsync(ClienteSynchro.ServerJava.AgregarConocimientoRequest request) {
            return base.Channel.AgregarConocimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.AgregarConocimientoResponse> AgregarConocimientoAsync(string nombre, string usuario) {
            ClienteSynchro.ServerJava.AgregarConocimientoRequest inValue = new ClienteSynchro.ServerJava.AgregarConocimientoRequest();
            inValue.nombre = nombre;
            inValue.usuario = usuario;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).AgregarConocimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSynchro.ServerJava.VerificarUsuarioResponse ClienteSynchro.ServerJava.PenduloWS.VerificarUsuario(ClienteSynchro.ServerJava.VerificarUsuarioRequest request) {
            return base.Channel.VerificarUsuario(request);
        }
        
        public bool VerificarUsuario(string usuario, string pass) {
            ClienteSynchro.ServerJava.VerificarUsuarioRequest inValue = new ClienteSynchro.ServerJava.VerificarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            ClienteSynchro.ServerJava.VerificarUsuarioResponse retVal = ((ClienteSynchro.ServerJava.PenduloWS)(this)).VerificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSynchro.ServerJava.VerificarUsuarioResponse> ClienteSynchro.ServerJava.PenduloWS.VerificarUsuarioAsync(ClienteSynchro.ServerJava.VerificarUsuarioRequest request) {
            return base.Channel.VerificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSynchro.ServerJava.VerificarUsuarioResponse> VerificarUsuarioAsync(string usuario, string pass) {
            ClienteSynchro.ServerJava.VerificarUsuarioRequest inValue = new ClienteSynchro.ServerJava.VerificarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.pass = pass;
            return ((ClienteSynchro.ServerJava.PenduloWS)(this)).VerificarUsuarioAsync(inValue);
        }
    }
}
